"""
Django settings for composeexample project.

Generated by 'django-admin startproject' using Django 2.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
"""


18.220.254.196

(myprojectenv) ubuntu@ip-172-31-34-200:~/myproject/AWSdjango_ec2$ cat /etc/systemd/system/gunicorn.service
[Unit]
Description=gunicorn daemon
After=network.target
[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/myproject/AWSdjango_ec2
ExecStart=/home/ubuntu/myproject/myprojectenv/bin/gunicorn --workers 3 --bind unix:/home/ubuntu/myproject/AWSdjango_ec2.sock composeexample.wsgi:application
[Install]
WantedBy=multi-user.target
(myprojectenv) ubuntu@ip-172-31-34-200:~/myproject/AWSdjango_ec2$


(myprojectenv) ubuntu@ip-172-31-34-200:~/myproject/AWSdjango_ec2$ ls
AWSD  Dockerfile  README.md  __init__.py  __pycache__  composeexample  db.sqlite3  djangofirst  docker-compose.yml  drf  manage.py  requirements.txt  static  templates
(myprojectenv) ubuntu@ip-172-31-34-200:~/myproject/AWSdjango_ec2$


sudo systemctl start gunicorn
sudo systemctl enable gunicorn


           └─21845 /home/ubuntu/myproject/myprojectenv/bin/python /home/ubuntu/myproject/myprojectenv/bin/gunicorn --workers 3 --bind unix:/home/ubuntu/myproject/AWSdjango_

Jun 09 20:26:22 ip-172-31-34-200 systemd[1]: Stopped gunicorn daemon.
Jun 09 20:26:22 ip-172-31-34-200 systemd[1]: Started gunicorn daemon.
Jun 09 20:26:23 ip-172-31-34-200 gunicorn[21819]: [2020-06-09 20:26:23 +0000] [21819] [INFO] Starting gunicorn 20.0.4
Jun 09 20:26:23 ip-172-31-34-200 gunicorn[21819]: [2020-06-09 20:26:23 +0000] [21819] [INFO] Listening at: unix:/home/ubuntu/myproject/AWSdjango_ec2.sock (21819)
Jun 09 20:26:23 ip-172-31-34-200 gunicorn[21819]: [2020-06-09 20:26:23 +0000] [21819] [INFO] Using worker: sync
Jun 09 20:26:23 ip-172-31-34-200 gunicorn[21819]: [2020-06-09 20:26:23 +0000] [21839] [INFO] Booting worker with pid: 21839
Jun 09 20:26:23 ip-172-31-34-200 gunicorn[21819]: [2020-06-09 20:26:23 +0000] [21843] [INFO] Booting worker with pid: 21843
Jun 09 20:26:23 ip-172-31-34-200 gunicorn[21819]: [2020-06-09 20:26:23 +0000] [21845] [INFO] Booting worker with pid: 21845



"""
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")
STATIC_DIR = os.path.join(BASE_DIR, "static")
# import pdb;pdb.set_trace()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bh0s#9lb(uww=hbloha1y7+=rq4t36*(+898y#noq)#a0dg$ji'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["18.220.254.196"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'djangofirst',
    'drf',
    "AWSD"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'composeexample.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'composeexample.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS =[
    STATIC_DIR,
]
