# Generated by Django 2.2.12 on 2020-06-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AWSD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersmodel',
            name='Members_periods',
        ),
        migrations.AddField(
            model_name='membersmodel',
            name='Members_periods',
            field=models.ManyToManyField(null=True, related_name='items', to='AWSD.ActivityModel'),
        ),
    ]
